# Docker compose file for local testing.
version: '3'
services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-storage:
    external: true
